### ISSUE TITLE
how can calculate the manhattan line for LayoutNetv2 input?

### ISSUE THREAD

**Issue by godhj93** [zouchuhang/LayoutNetv2#11]
Hi! I have trained the network and it successfully find the boundaries and corner points.

I want to use the network for my custom input however it requires manhattan lines for input as well.

so I want to know how to get the lines. is there any source code?

thanks!

**Comment by zouchuhang** [comment]
@godhj93 Here's a python implementation to extract Manhattan Lines: https://github.com/sunset1995/pytorch-layoutnet#2-pre-processing-align-camera-pose-with-floor
